### ISSUE TITLE
[sort-package-xml] Ignore conditions

### ISSUE THREAD

**Issue by Timple** [tier4/pre-commit-hooks-ros#86]
On some hybrid ROS 1/ROS 2 packages we use conditions. However I like to sort on dependency, not on xml tag:

So this:
```xml
  <depend>actionlib_msgs</depend>
  <depend condition="$ROS_VERSION == 1">can_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
```

Instead of this:

```xml
  <depend>actionlib_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend condition="$ROS_VERSION == 1">can_msgs</depend>
```

Would this make a nice addition? Or do you have other insights?

**Comment by kenji-miyake** [comment]
@Timple Thank you for your suggestion!

We follow the existing rules in the following cases, but otherwise, we can accept it if it is consistent.
- The rule is explicitly defined in ROS's guidelines.
- The rule is implicitly conventionalized by the existing packages.
- The rule is written in http://download.ros.org/schema/package_format3.xsd.

In this case, since most packages seem not to care about the order so much, I think your suggestion is acceptable.

cc @KeisukeShima
